name: face_recognition_system
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8
  image: ^4.1.7
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_commons: ^0.7.1
  tflite_flutter: ^0.10.4
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: any
#  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/tflite_models

